---
title: "HCA Harmonised"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{readme}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
# Note: knit this to the repo readme file using:
# rmarkdown::render("vignettes/readme.Rmd", output_format = "github_document", output_dir = getwd())
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```


Load the package

```{r, message=FALSE, warning=FALSE}
library(HCAquery)
library(dplyr)
```

Load the metadata

```{r}
get_metadata()
```

Explore the HCA content

```{r}
get_metadata() |>
    distinct(tissue, file_id) |>
    count(tissue) |>
    arrange(desc(n))
```

Query raw counts

```{r}
library(stringr)
sce <-
    get_metadata() |>
    filter(
        ethnicity == "African" &
        str_like(assay, "%10x%") &
        tissue == "lung parenchyma" &
        str_like(cell_type, "%CD4%")
    ) |>
    get_SingleCellExperiment()

sce
```

Query counts scaled per million. This is helpful if just few genes are of interest

```{r}
sce <-
    get_metadata() |>
    filter(
        ethnicity == "African" &
        str_like(assay, "%10x%") &
        tissue == "lung parenchyma" &
        str_like(cell_type, "%CD4%")
    ) |>
    get_SingleCellExperiment(assays = "cpm")

sce
```

Extract only a subset of genes:

```{r}
get_metadata() |>
    filter(
        ethnicity == "African" &
        str_like(assay, "%10x%") &
        tissue == "lung parenchyma" &
        str_like(cell_type, "%CD4%")
    ) |>
    get_SingleCellExperiment(features = "PUM1")
```

Extract the counts as a Seurat object:

```{r}
get_metadata() |>
    filter(
        ethnicity == "African" &
        str_like(assay, "%10x%") &
        tissue == "lung parenchyma" &
        str_like(cell_type, "%CD4%")
    ) |>
    get_seurat()
```
```{r}
sessionInfo()
```

